--- 
title: "Efficient R programming Book Club"
date: "Rendered: `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-efficientr
description: "This website is the product of the R4DS Online Learning Community's Efficient R programming Book Club."
---

# Welcome {-}

This website is a companion for the book [***Efficient R programming***](https://csgillespie.github.io/efficientR/index.html) by **Colin Gillespie &  Robin Lovelace** (copyright 2021).

-   These are **shared slides!**
    -   Developed by the [**R4DS Online Learning Community**](https://rfordatasci.com).
    -   [**Join the community**](https://r4ds.io/join) to participate!
    -   Available at [**r4ds.io/efficientr**](https://r4ds.io/efficientr).
-   We follow the [**R4DS Online Learning Community Code of Conduct**](https://r4ds.io/conduct).

## Pace {-}

-   Meet **every week.**
    -   I don't see skip-requiring holidays.
    -   Try to **always meet** (even if not ready).
-   **1 chapter/week**
-   ...Split chapters when they feel like too much.

## Format {-}

-   [**Volunteer to present!**](https://docs.google.com/spreadsheets/d/14ZEsvT-qaNRCvdJk_IXMLbZ_gXF4wJeSMlhNJNobhQs/edit?usp=sharing)
    -   **This is the best way to learn the material!**
-   Format up to you!
    -   Review, discussion, demonstration, combo.
-   Ideally **update shared slides**.
    -   Instructions in [github repo](https://github.com/r4ds/bookclub-efficientr).
-   Presentations **recorded** & available on [**R4DS Online Learning Community YouTube Channel**](https://r4ds.io/youtube).
